Traceback (most recent call last):
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/nileshkr/.conda/envs/sparknlp/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
os.environ["JAVA_HOME"] = os.environ["JAVA_HOME"]
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mJAVA_HOME[39m[38;5;124m"[39m] [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mJAVA_HOME[39;49m[38;5;124;43m"[39;49m[43m][49m
[1;32m      2[0m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mPATH[39m[38;5;124m"[39m] [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mJAVA_HOME[39m[38;5;124m"[39m] [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/bin:[39m[38;5;124m"[39m [38;5;241m+[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mPATH[39m[38;5;124m"[39m]

File [0;32m~/.conda/envs/sparknlp/lib/python3.8/os.py:675[0m, in [0;36m_Environ.__getitem__[0;34m(self, key)[0m
[1;32m    672[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;28mself[39m[38;5;241m.[39mencodekey(key)]
[1;32m    673[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[1;32m    674[0m     [38;5;66;03m# raise KeyError with the original key value[39;00m
[0;32m--> 675[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;28mNone[39m
[1;32m    676[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mdecodevalue(value)

[0;31mKeyError[0m: 'JAVA_HOME'
KeyError: 'JAVA_HOME'

